export const BALANCE = {
  startHp: 28,
  startCash: 8,
  restHeal: 8,
  maxRounds: 12,
  fightCash: 4,
  eliteCash: 8,
  minChip: 2,
  fightHp: [24, 28] as const,
  fightAtk: [8, 7] as const,
  eliteHp: [36, 40] as const,
  eliteAtk: [10, 9] as const,
  bossHp: 56,
  bossAtk: 12,
  lightMax: 32,
  heavyMin: 48,
  floor1HeavyMin: 22,
  lateHeavyMin: 56,
} as const;
